data_processing:
  input_compat_data_folder: '/Users/adamfletcher/Documents/GitHub/defra_geojson/Compatibility_checker/' 
  input_compat_excel_filename: 'Option compat matrix 24 updated 29 May.xlsx'
  sfi_actions_folder: /Users/adamfletcher/Documents/GitHub/defra_geojson/actions/
